params:
  light:
    bg: '#fff'
    accentBg: '#f5f7ff'
    text: '#212121'
    textLight: '#585858'
    border: '#d8dae1'
    accent: '#0d47a1'
    code: '#d81b60'
    preformatted: '#444'
    marked: '#ffdd33'
    disabled: '#efefef'
  dark:
    bg: '#212121'
    accentBg: '#2b2b2b'
    text: '#dcdcdc'
    textLight: '#ababab'
    border: '#666'
    accent: '#ffb300'
    code: '#f06292'
    preformatted: '#ccc'
    marked: '#ffdd33'
    disabled: '#111'
